server:
  port: 9001
spring:
  application:
    name: provider-service #这个name 会在注册中心中显示

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true，注册中心的才为false
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群版  eureka8001.com是在hosts文件中设置映射地址
      #defaultZone: http://eureka8001.com:8001/eureka/,http://eureka7002.com:7002/eureka/
      #单机版        http://eureka8001.com:8001/eureka/
      defaultZone: http://localhost:8001/eureka/ #,http://localhost:8002/eureka/
  instance:
    instance-id: provider9001  #主机名的修改
    prefer-ip-address: true #访问路径可以显示ip  #访问路径可以显示 ip地址 在eureka页面上 需要健康检查依赖
    #Eureka客户端向服务端发送心跳的实际间隔，单位为秒（默认为30秒）
    # 默认发送心跳是30s一次  现在测试eureka的自我保护机制 改成1s一次
    lease-renewal-interval-in-seconds: 1 #续约更新时间间隔，一般设置比续约到期时间少，该配置表示，每隔多少秒就向服务端发送心跳。
    #eureka服务在 在收到最后一次心跳后等待时间上限， 单位为秒(默认是90秒)， 超时将刷除服务
    lease-expiration-duration-in-seconds: 2 #续约到期时间，可以单独给每个服务设置，如果在多少秒 内没有给服务发送心跳，则剔除该服务。

