server:
  port: 8001

#单机模式
eureka:
  instance:
    hostname: hostname
  client:
    fetch-registry: false #是否向注册中心注册自己 ，因为自己就是注册中心 所以不用向自己注册自己
    register-with-eureka: false  # 发现服务列表，因为自己是注册中心 所以不用发现
    serviceUrl:
      #单机版注册地址  如果是集群，则把后面的值改成其它的注册中心对应的地址
      defaultZone: http://localhost:8002/eureka/


