


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true，注册中心的才为false
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群版  eureka8001.com是在hosts文件中设置映射地址
      #defaultZone: http://eureka8001.com:8001/eureka/,http://eureka7002.com:7002/eureka/
      #单机版        http://eureka8001.com:8001/eureka/
      defaultZone: http://localhost:8001/eureka/ #,http://localhost:8002/eureka/
  instance:
    instance-id: openFeign-Consumer-8080  #主机名的修改
    prefer-ip-address: true #访问路径可以显示ip
    #Eureka客户端向服务端发送心跳的实际间隔，单位为秒（默认为30秒）
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端收到最后一次心跳后等待时间上线，单位为秒（默认为90秒） 超时将剔除服务
    lease-expiration-duration-in-seconds: 90
spring:
  application:
    name: consumer-service

server:
  port: 8080

#设置feign客户端超时时间（OpenFeign默认支持ribbon 所以直接配置成ribbon的即可）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的实际
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic

logging:
  level:
    #feign日志以什么级别监控那个接口
    com.li.service.OpenFeignService: debug